# Generated by Django 5.0.4 on 2024-06-09 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_alter_news_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='image',
            new_name='image_url',
        ),
    ]
