# Generated by Django 5.0.4 on 2024-06-09 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_rename_image_news_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='unique_identifier',
            field=models.CharField(default='default_value_here', max_length=255, unique=True),
        ),
    ]
